### ISSUE TITLE
模拟器摄像头打开同意了 但是没拍摄？

### ISSUE THREAD

**Issue by NexusLee** [GrayJIAXU/520Linkee#3]
![18ad57f6-8cbc-434d-afaa-f3d6165f9b8c](https://cloud.githubusercontent.com/assets/4703440/17044115/8bd17074-4fef-11e6-8449-b95cf5f9724f.png)

**Comment by jiaair** [comment]
用真机才能打开摄像头，我会修复这个bug。

发自我的 iPhone

在 2016年7月22日，09:36，NexusLee <notifications@github.com<mailto:notifications@github.com>> 写道：

[18ad57f6-8cbc-434d-afaa-f3d6165f9b8c]https://cloud.githubusercontent.com/assets/4703440/17044115/8bd17074-4fef-11e6-8449-b95cf5f9724f.png

―

**Comment by NexusLee** [comment]
@GrayJIAXU  好吧 谢谢 我自己再去琢磨琢磨 :(
